title: Charles M
description: Personal collection of notes and guides to various computational chemistry and structural techniques
theme: just-the-docs

url: https://ckmin45.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
